In [1]:
import tensorflow as tf

In [2]:
lm_hparams = tf.contrib.training.HParams(
    num_phyche_features=7,
    train_file="/home/dillon/data/cUR50/cUR50_train.tfrecords",
    batch_size=1,
    num_epochs=1,
    lm_kind="fw",
    model="lm")
bdrnn_hparams = tf.contrib.training.HParams(
    num_phyche_features=7,
    train_file="/home/dillon/data/cpdb2/cpdb_train.tfrecords",
    batch_size=1,
    num_epochs=1,
    model="bdrnn")

In [3]:
from lm_pretrain.dataset import create_dataset

In [4]:
lm_fw_dataset = create_dataset(lm_hparams, tf.contrib.learn.ModeKeys.TRAIN)
iterator = lm_fw_dataset.make_initializable_iterator()
_id, _len, _seq, _phyche, _, _tar = iterator.get_next()

In [5]:
with tf.Session() as sess:
    sess.run([tf.tables_initializer()])
    sess.run([iterator.initializer])
    id, len, seq, phyche, tar = sess.run([_id, _len, _seq, _phyche, _tar])

In [6]:
print(seq[0, 0:5])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [7]:
print(phyche[0, 0:5])

[[ 1.          0.74086356 -0.16368844 -0.12355296 -0.46572044  0.14045486
   0.47695956]
 [ 2.         -1.0531559  -1.6408768  -0.28470898 -0.09314409 -2.0098314
  -0.19078383]
 [ 0.          0.707641   -0.00969583  1.0582579   0.6912272  -0.8386116
  -1.1447029 ]
 [ 1.          1.504983   -0.01539926  1.2731326   0.4363065   1.3482752
  -0.28617573]
 [ 1.          1.3720926  -0.00969583  0.95082057  0.4363065   0.36005855
   0.19078383]]


In [8]:
print(len)

[269]


In [9]:
bdrnn_dataset = create_dataset(bdrnn_hparams, tf.contrib.learn.ModeKeys.TRAIN)
iterator2 = bdrnn_dataset.make_initializable_iterator()
sample = iterator2.get_next()

In [10]:
with tf.Session() as sess:
    sess.run([tf.tables_initializer()])
    sess.run([iterator2.initializer])
    id, len, seq, phyche, pssm, tar = sess.run(sample)

In [11]:
print(len)

[501]


In [12]:
print(seq[0, 0:5])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [13]:
print(pssm[0, 0:5])

[[0.05069032 0.03106848 0.00527231 0.0163025  0.13124447 0.00784502
  0.02608408 0.4304538  0.03229546 0.61774784 0.99994886 0.01378899
  0.00985375 0.08317269 0.03167623 0.02819529 0.06660803 0.24601129
  0.03017798 0.26894143 0.04787969]
 [0.05166143 0.00532502 0.7595109  0.6921095  0.00415202 0.07798824
  0.3078905  0.00570892 0.99685884 0.00689527 0.02366058 0.73885
  0.07798824 0.9556382  0.32959884 0.58419055 0.08948006 0.01177421
  0.00486893 0.26894143 0.01567329]
 [0.00800223 0.00892442 0.00150118 0.00407014 0.98964626 0.00162601
  0.13470304 0.0198403  0.00532502 0.22443599 0.02508696 0.00383402
  0.0017437  0.00724624 0.02685712 0.00636851 0.01131776 0.10065208
  0.23685499 0.26894143 0.9998703 ]
 [0.04109127 0.02484354 0.00259907 0.00368424 0.04742587 0.0019076
  0.00257327 0.99795437 0.00543201 0.38936076 0.3941263  0.00284314
  0.00482072 0.00543201 0.00407014 0.00892442 0.04742587 0.99363154
  0.00445173 0.26894143 0.01945508]
 [0.63645256 0.03324631 0.00792324 0.0127423

In [14]:
print(tar[0, 0:5])

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
