In [1]:
import tensorflow as tf

In [2]:
lm_hparams = tf.contrib.training.HParams(
    num_phyche_features=7,
    train_file="/home/dillon/data/cUR50/cUR50_train.tfrecords",
    batch_size=1,
    num_epochs=1,
    lm_kind="fw",
    model="lm")
bdrnn_hparams = tf.contrib.training.HParams(
    num_phyche_features=7,
    train_file="/home/dillon/data/cpdb2/cpdb_train.tfrecords",
    batch_size=1,
    num_epochs=1,
    model="bdrnn")

In [3]:
from lm_pretrain.dataset import create_dataset

In [4]:
lm_fw_dataset = create_dataset(lm_hparams, tf.contrib.learn.ModeKeys.TRAIN)
iterator = lm_fw_dataset.make_initializable_iterator()
(_id, _len, _seq, _phyche, _), _tar = iterator.get_next()

In [5]:
with tf.Session() as sess:
    sess.run([tf.tables_initializer()])
    sess.run([iterator.initializer])
    id, len, seq, phyche, tar = sess.run([_id, _len, _seq, _phyche, _tar])

In [6]:
print(seq[0, 0:5])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [7]:
print(phyche[0, 0:5])

[[ 1.          0.74086356 -0.16368844 -0.12355296 -0.46572044  0.14045486
   0.47695956]
 [ 2.         -1.3853817   2.6994333  -1.7888318  -1.0343896   0.13130471
   1.1447029 ]
 [ 0.         -0.02325581  0.01882132  1.0582579   0.5147436  -2.0098314
  -1.6216625 ]
 [ 1.          0.9401991  -0.5572251  -1.2516451   2.3187976  -0.39025408
  -0.38156766]
 [ 1.          1.3720926  -0.00969583  0.95082057  0.4363065   0.36005855
   0.19078383]]


In [8]:
print(len)

[82]


In [9]:
bdrnn_dataset = create_dataset(bdrnn_hparams, tf.contrib.learn.ModeKeys.TRAIN)
iterator2 = bdrnn_dataset.make_initializable_iterator()
sample = iterator2.get_next()

In [11]:
with tf.Session() as sess:
    sess.run([tf.tables_initializer()])
    sess.run([iterator2.initializer])
    (id, len, seq, phyche, pssm), tar = sess.run(sample)

In [12]:
print(len)

[359]


In [13]:
print(seq[0, 0:5])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [14]:
print(pssm[0, 0:5])

[[0.7170753  0.09534947 0.159762   0.23685499 0.02209632 0.15187116
  0.10812867 0.03106848 0.21416503 0.02819529 0.07516011 0.31216866
  0.10433122 0.84290457 0.13470304 0.99477994 0.87435216 0.06660803
  0.01746392 0.5        0.04787969]
 [0.1809388  0.0801729  0.0765622  0.15058757 0.77902615 0.08471056
  0.7271082  0.13705128 0.25730947 0.36354747 0.12238888 0.39174098
  0.9976941  0.8347951  0.09195455 0.22270013 0.27888483 0.117119
  0.04608883 0.11920292 0.5670929 ]
 [0.41095954 0.0104567  0.38936076 0.9967956  0.00947104 0.05069032
  0.2332589  0.01224884 0.876533   0.01582831 0.04031041 0.15446526
  0.10156092 0.81757444 0.54983395 0.29943287 0.45016602 0.026597
  0.01237041 0.26894143 0.03106848]
 [0.22097391 0.02508696 0.7595109  0.9677046  0.2650274  0.06122616
  0.80533844 0.2158528  0.6659669  0.11405239 0.45760205 0.850687
  0.24787088 0.9241418  0.3208213  0.40131235 0.50749946 0.09534947
  0.7088902  0.26894143 0.11304584]
 [0.15446526 0.0114302  0.4750208  0.9916739  

In [15]:
print(tar[0, 0:5])

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
